version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 10
      python: 3.7
  pre_build:
    commands:
      - 'npm install -g aws-cdk'
      - 'pip install --upgrade pip'
      - 'pip install -r requirements.txt'
  build:
    commands:
      - 'cdk deploy "*" --context stack=$ENV --require-approval never'
  post_build:
    commands:
      - 'printf {"ImageURI":"image_URI"} > imageDetail.json'
      - 'printf [{"name":"hello-world","imageUri":"%s"}] $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json'
artifacts:
  files:
    - imageDetail.json
    - imagedefinitions.json
cache:
  paths:
  - '~/.docker-cache/**/*'
  - '~/.cache/**/*'
  - '~/.npm/**/*'
